.github/workflows/gradle.yml
src/main/java/kr/co/antoon/common/dto/ResponseDto.java
src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
src/main/java/kr/co/antoon/discussion/domain/Discussion.java
src/main/java/kr/co/antoon/discussion/dto/request/DiscussionCreateRequest.java
src/main/java/kr/co/antoon/discussion/dto/request/DiscussionUpdateRequest.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionCreateResponse.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionReadResponse.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionUpdateResponse.java
src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
src/main/java/kr/co/antoon/error/GlobalExceptionHandler.java
src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
src/main/java/kr/co/antoon/error/exception/common/NotExistsException.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
src/test/java/kr/co/antoon/AntoonApplicationTests.java
src/test/java/kr/co/antoon/discussion/application/DiscussionServiceTest.java

✨ [Feature/discussion-12] 종토방 기능 구현

---

src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
src/main/java/kr/co/antoon/discussion/domain/Discussion.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionCreateResponse.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionReadResponse.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionUpdateResponse.java
src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
src/main/java/kr/co/antoon/like/application/LikeService.java
src/main/java/kr/co/antoon/like/domain/Like.java
src/main/java/kr/co/antoon/like/facade/LikeFacade.java
src/main/java/kr/co/antoon/like/infrastructure/LikeRepository.java
src/main/java/kr/co/antoon/like/presentation/LikeController.java
src/test/java/kr/co/antoon/discussion/application/DiscussionServiceTest.java
src/test/java/kr/co/antoon/like/application/LikeServiceTest.java
src/test/java/kr/co/antoon/like/infrastructure/LikeControllerTest.java

종토방(댓글) 좋아요 구현
- resolved #16
* 좋아요 구현
* 좋아요 카운트
* 로그인한 유저가 해당 댓글에 좋아요 했는지 여부 체크
단위테스트는 정상 작동합니다.
통합테스트 실행 시 아래와 같은 오류가 발생합니다.
```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [kr.co.antoon.webtoon.crawling.KakaoWebtoonCrawling] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7]
```
카카오크롤링에서 문제가 발생하는거 같은데 어떻게 해결하면 좋을까요 
* API 주소 재설정
* @PutMapping으로 수정
* 파사드 패턴 적용
* 0님께서 수정해주셔서 통합테스트 코드 정상 작동됨. 감삼다 :+1: 
* 파사드 패턴 적용해봤는데 이렇게 적용하는거 맞나요?
* LikeFacade에서 likeService.saveOrUpdate()에 disscusion 값을 넘겨줘도 되나요?
* likeService.saveOrUpdate()에서 discussion의 likeCount 값을 업데이트 하기 위함 입니다.
* discussion의 likeCount 업데이트는 LikeService에서 해야할까요, 아님 LikeFacade에서 해야할까요?

✨ [Feature/like] 종토방 좋아요 구현

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- resolved #56 
깃허브에서 권고하는 정책 파일 추가

✨ [Feature/GitHub convention-56] 깃허브 정책 파일 추가

---

src/main/java/kr/co/antoon/common/domain/SlackCrusier.java
src/main/java/kr/co/antoon/common/dto/SlackCrusierDto.java
src/main/java/kr/co/antoon/config/properties/SlackCrusierProperties.java

- resolved #58 
- 모니터링용 슬랙 알림 모듈입니다.
- 변수명이 조금 어색한 것 같아요 추천 부탁드려요 ㅜ

✨ [Feature/crusier-monitoring-58] 모니터링용 슬랙 알림 모듈

---

src/main/java/kr/co/antoon/webtoon/application/WebtoonGenreService.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
src/main/java/kr/co/antoon/webtoon/domain/WebtoonPublishDay.java
src/main/java/kr/co/antoon/webtoon/domain/vo/Platform.java
src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonAllResponse.java
src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonResponse.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java

✨ [Feature/webtoon-64] 웹툰 조회 공통 dto

---

src/main/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawling.java
src/test/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawlingTest.java

- 카카오웹툰에서 크롤링하는 요일, 장르를 수정합니다.
- resolved #9 
- 카카오웹툰에서 크롤링하는 요일, 장르를 수정합니다.

:bug: 카카오 웹툰 요일값 수정

---

src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
src/main/java/kr/co/antoon/oauth/presentation/LoginController.java

✨[Feature/oauth-config-69] 로그인 핸들러 테스트

---

src/main/java/kr/co/antoon/batch/cruiser/CruiserBatchScheduler.java
src/main/java/kr/co/antoon/batch/cruiser/CruiserHourJob.java
src/main/java/kr/co/antoon/batch/graph/GraphScoreBatchScheduler.java
src/main/java/kr/co/antoon/batch/recommendation/RecommendationBatchScheduler.java
src/main/java/kr/co/antoon/batch/webtoon/WebtoonCrawlingBatchScheduler.java
src/main/java/kr/co/antoon/common/Utility.java
src/main/java/kr/co/antoon/cruiser/domain/SlackCruiser.java
src/main/java/kr/co/antoon/cruiser/dto/slack/SlackCruiserResponse.java
src/main/java/kr/co/antoon/cruiser/facade/CruiserFacade.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java

- resolved #80 
- 슬랙 모니터링 서비스 개선 작업 진행
- 배치 프로파일 상태 정의
- 간단 수정이어서 바로 머지 진행할게요

✨ [Feature/monitoring-80] 모니터링 서비스 추가 및 배치 수정

---

src/main/java/kr/co/antoon/common/presentation/HealthController.java
src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
src/main/java/kr/co/antoon/graph/application/TopRankService.java
src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
src/main/java/kr/co/antoon/graph/domain/ScoreAllocationCriteria.java
src/main/java/kr/co/antoon/graph/domain/vo/RankReason.java
src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
src/main/java/kr/co/antoon/recommendation/infrastructure/RecommendationCountRepository.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonSnapshotService.java
src/main/java/kr/co/antoon/webtoon/domain/WebtoonGenre.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonSnapshotRepository.java

- resolved #70 
- 그래프 스코어 기능을 수정합니다.
- 랭킹 알고리즘을 수정합니다.

🐛 [Improve/graph-score-70] 그래프 스코어 기능 수정

---

src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
src/main/java/kr/co/antoon/recommendation/infrastructure/RecommendationCountRepository.java

- RecommendationCount 엔티티 수정
- resolved #11 
- RecommendationCount 엔티티에서 UserId가 필요없다고 판단되어 변경

♻️ [Refactor/recommendation-11] RecommendationCount Entity 수정

---

src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonDayResponse.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java

요일별 웹툰 조회 API
- resolved #33 
* 요일별 웹툰 조회
* 상승폭 정렬
* size 12로 페이징 처리

✨ [Feature/day-33] 요일별 웹툰 조회 API

---

src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
src/main/java/kr/co/antoon/oauth/presentation/LoginController.java
src/main/java/kr/co/antoon/user/domain/User.java

- resolved #82 
- 카카오 로그인 시 성별과 연령대를 받아와서 DB에 저장한다

:sparkles: [Feature/oauth-addInfo-82] 카카오 로그인 시 성별, 연령대 정보 받아오기

---

src/main/java/kr/co/antoon/common/presentation/HealthController.java
src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
src/main/java/kr/co/antoon/discussion/dto/DiscussionCountDto.java
src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
src/main/java/kr/co/antoon/graph/dto/response/TopRankResponse.java
src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
src/main/java/kr/co/antoon/graph/facade/TopRankFacade.java
src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
src/main/java/kr/co/antoon/graph/presentation/TopRankController.java
src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
src/main/java/kr/co/antoon/recommendation/infrastructure/RecommendationCountRepository.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonSnapshotService.java
src/main/java/kr/co/antoon/webtoon/crawling/NaverWebtoonCrawling.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java

- resolved #47 
- 실시간 차트에 대한 리펙토링을 진행합니다.
- 배치로직을 수정합니다.

✨ [Feature/graph-47] 실시간 차트에 대한 리펙토링을 진행합니다

---

src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java

♻️ [Refactor/webtoon detail] 존재하지 않는 웹툰 조회 시 발생하는 오류 메시지 수정

---

src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
src/main/java/kr/co/antoon/graph/domain/vo/Period.java
src/main/java/kr/co/antoon/graph/dto/response/GraphScoreResponse.java
src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
src/main/java/kr/co/antoon/graph/presentation/GraphScoreController.java

- resolved #49 
- 하루, 일주일, 한달, 세달 기간동안의 웹툰 접수 스냅샷 정보를 조회

✨ [Feature/graph-49] 기간별 웹툰 스코어 조회

---

src/main/java/kr/co/antoon/discussion/application/DiscussionLikeService.java
src/main/java/kr/co/antoon/discussion/domain/DiscussionLike.java
src/main/java/kr/co/antoon/discussion/facade/DiscussionLikeFacade.java
src/test/java/kr/co/antoon/like/application/LikeServiceTest.java

- resolved #101 
* 댓글에 좋아요 없는 경우 고려해 댓글 조회 수정
* 테스트 작성

🐛 [Fix/descussion like-101] 댓글 좋아요 수정 및 테스트

---

src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/user/application/UserService.java
src/main/java/kr/co/antoon/user/dto/request/UserDetailRequest.java
src/main/java/kr/co/antoon/user/presentation/UserController.java

마이페이지 수정 api 구현
- resolved #84

:sparkles: [Feature/modify-mypage] 마이페이지(닉네임, 프로필 이미지) 수정 api 구현

---

src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java

로그인 시 토큰 전달 하는 부분 쿼리스트링으로 수정했습니다
- resolved #0

:recycle: [Refactor/login] 토큰 전달 부분 쿼리스트링으로 변경

---

src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java

- resolved #0
- 로그인 부분에서 필요 없는 코드 삭제
- 프론트와 연동 후 머지 예정

:recycle: [Feature/login2] 헤더와 쿠키 부분에 토큰 삭제

---

src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java

- redis의 key 값을 unique하게 변경합니다
- resolved #0

:recycle: [Feature/oauth_redis] redis key값 unique하게 변경

---

.github/PULL_REQUEST_TEMPLATE.md
src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/config/SwaggerConfig.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
src/main/java/kr/co/antoon/webtoon/dto/WebtoonDayNativeDto.java
src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonDayResponse.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java

- resolved #109 
- api 성능 개선 작업
- swagger config 수정

⚡️ [Improve/all-109] 성능 개선 및 swagger 수정

---

src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
src/main/java/kr/co/antoon/recommendation/application/RecommendationService.java
src/main/java/kr/co/antoon/recommendation/domain/Recommendation.java
src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java

- 탑승하차 API 리팩토링
- resolved #115 
- @AuthUser 변경사항 반영
- TODO 주석 부분 수정
- 금일 API 연동을 위해 API 하나로 합치는 작업은 아직 못했습니다ㅠ

♻️ [Refactor/recommendation 115] 탑승해요 하차해요 코드 리팩토링 

---

src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionResponse.java
src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
src/main/java/kr/co/antoon/oauth/config/LoginUserArgumentResolver.java

- resolved #118 
* 로그인 안한 사용자도 댓글 조회 가능하도록 수정
* response에 웹툰 ID 추가
* DiscussionFacade의 findAll 메서드를 좀 더 깔끔하게 작성할 방법이 없을까용
* 로그인 여부 구분을 위해 AuthInfo가 null인지 체크해야돼서 중복되는 코드를 넣었습니다.
*  좋은 방법이 있다면 리뷰 부탁드립니다!

🐛[Fix/discussion-118] 댓글 조회 API 권한 수정

---

src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonAgeResponse.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java

- resolved #121 
- mock api 추가

✨ [Feature/age-121] 연령대별 인기 웹툰 조회 mock api 추가

---

src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
src/main/java/kr/co/antoon/user/domain/User.java
src/main/java/kr/co/antoon/user/domain/vo/Gender.java
src/main/java/kr/co/antoon/user/infrastructure/UserRepository.java

- resolved #0
- 회원가입 시 정책동의 절차 진행을 위해 redirect url의 stattus를 변경
- status=signup : 첫 로그인 / status=success : 로그인 성공

⚡️ [Feature/login-agree] 로그인 시 정책 동의를 위한 status 변경

---

src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
src/main/java/kr/co/antoon/config/ScoreAllocationCriteriaConfig.java
src/main/java/kr/co/antoon/config/SecurityConfig.java
src/main/java/kr/co/antoon/config/properties/SlackCruiserProperties.java
src/main/java/kr/co/antoon/criteria/BasicAllocateScore.java
src/main/java/kr/co/antoon/criteria/ScoreAllocationCriteria.java
src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
src/main/java/kr/co/antoon/oauth/filter/JwtFilter.java
src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
src/main/java/kr/co/antoon/webtoon/domain/WebtoonGenre.java
src/main/java/kr/co/antoon/webtoon/domain/WebtoonPublishDay.java
src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreResponse.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java

⚡️ [Improve/all-125] 앙뚜앙 대격변

---

src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
src/main/java/kr/co/antoon/recommendation/domain/vo/RecommendationStatus.java
src/main/java/kr/co/antoon/recommendation/dto/response/RecommendationResponse.java
src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java

- resolved #128 
* 탑승/하차 API 반환값 추가
* 탑승/하차 API 병합

🐛[Fix/recommendation-128] 탑승/하차 API 반환값 추가 및 리팩토링

---

src/main/java/kr/co/antoon/common/presentation/HealthController.java
src/main/java/kr/co/antoon/criteria/BasicAllocateScore.java
src/main/java/kr/co/antoon/feedback/application/FeedbackService.java
src/main/java/kr/co/antoon/feedback/domain/Feedback.java
src/main/java/kr/co/antoon/feedback/domain/vo/Score.java
src/main/java/kr/co/antoon/feedback/domain/vo/Status.java
src/main/java/kr/co/antoon/feedback/dto/FeedbackResponse.java
src/main/java/kr/co/antoon/feedback/infrastructure/FeedbackRepository.java
src/test/java/kr/co/antoon/common/presentation/HealthControllerTest.java
src/test/java/kr/co/antoon/common/presentation/SwaggerControllerTest.java
src/test/java/kr/co/antoon/common/util/CommonUtilTest.java
src/test/java/kr/co/antoon/criteria/BasicAllocateScoreTest.java
src/test/java/kr/co/antoon/discussion/domain/DiscussionLikeTest.java
src/test/java/kr/co/antoon/discussion/domain/DiscussionTest.java
src/test/java/kr/co/antoon/feedback/application/FeedbackServiceTest.java
src/test/java/kr/co/antoon/feedback/domain/FeedbackTest.java
src/test/java/kr/co/antoon/feedback/domain/vo/ScoreTest.java
src/test/java/kr/co/antoon/feedback/facade/FeedbackFacadeTest.java
src/test/java/kr/co/antoon/feedback/presentation/FeedbackControllerTest.java
src/test/java/kr/co/antoon/graph/domain/vo/GraphStatusTest.java
src/test/java/kr/co/antoon/recommendation/domain/RecommendationCountTest.java

- resolved #140 
- 비즈니스 로직에 대한 테스트 코드 생성
- 테스트 코드를 작성하면서 잘못된 비즈니스 로직 수정 작업 진행

✅ [Test/all-140] 테스트 코드 작성 및 잘못된 비즈니스 로직 수정

---

src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
src/main/java/kr/co/antoon/webtoon/application/WebtoonGenreService.java
src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreAllResponse.java
src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonGenreRepository.java
src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java

⚡️ [Improve/main-page-api-142] top3 장르 조회 로직 수정 (top3 -> 임의값)

---

src/main/java/kr/co/antoon/coin/application/AntCoinHistoryService.java
src/main/java/kr/co/antoon/coin/application/AntCoinWalletService.java
src/main/java/kr/co/antoon/coin/domain/AntCoinHistory.java
src/main/java/kr/co/antoon/coin/domain/vo/RemittanceType.java
src/main/java/kr/co/antoon/coin/facade/AntCoinFacade.java
src/main/java/kr/co/antoon/coin/infrastructure/AntCoinWalletRepository.java
src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java

- resolved #150 
- 코인지갑 및 히스토리 기능 추가
- 회원가입시 코인 지갑 생성 기능 추가

⚡️ [Feature/mvp-2-150] 코인 지갑 및 기록 추적 기능

---

src/main/java/kr/co/antoon/common/presentation/SwaggerController.java
src/main/java/kr/co/antoon/config/SecurityConfig.java
src/main/java/kr/co/antoon/config/SwaggerConfig.java
src/main/java/kr/co/antoon/oauth/filter/JwtFilter.java

release v0.0.1

---

.github/workflows/gradle.yml
src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/common/presentation/SwaggerController.java
src/main/java/kr/co/antoon/config/SwaggerConfig.java
src/main/java/kr/co/antoon/oauth/application/AuthService.java
src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
src/main/java/kr/co/antoon/oauth/presentation/AuthController.java
src/main/java/kr/co/antoon/user/application/UserService.java
src/main/java/kr/co/antoon/user/domain/User.java
src/main/java/kr/co/antoon/user/domain/vo/Status.java
src/main/java/kr/co/antoon/user/dto/response/UserDetailResponse.java
src/main/java/kr/co/antoon/user/infrastructure/UserRepository.java
src/main/java/kr/co/antoon/user/presentation/UserController.java
src/test/java/kr/co/antoon/common/presentation/SwaggerControllerTest.java
src/test/java/kr/co/antoon/feedback/facade/FeedbackFacadeTest.java

release v0.0.2

---

.github/workflows/gradle.yml

release v0.0.3

---

src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
src/main/java/kr/co/antoon/discussion/converter/DiscussionConverter.java
src/main/java/kr/co/antoon/discussion/dto/response/DiscussionResponse.java
src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
src/test/java/kr/co/antoon/discussion/application/DiscussionServiceTest.java

release v0.0.4

---

src/main/java/kr/co/antoon/AntoonApplication.java

release v0.0.5

---

.gitignore
scripts/afterInstall.sh

포트 변경 및 gitignore 수정

---

.github/workflows/gradle.yml
.gitignore
Dockerfile
scripts/afterInstall.sh
scripts/beforeInstall.sh
src/main/java/kr/co/antoon/coin/application/AntCoinWalletService.java
src/main/java/kr/co/antoon/cruiser/dto/slack/SlackCruiserResponse.java
src/main/java/kr/co/antoon/cruiser/facade/CruiserFacade.java

release v0.0.7
